# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24bac162113225d71e4c458f5e51e049"
application_url = "https://kiss-webshots-accurate-threats.trycloudflare.com"
embedded = true
name = "digital_download_v2"
handle = "digital_download_v2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kiss-webshots-accurate-threats.trycloudflare.com/auth/callback",
  "https://kiss-webshots-accurate-threats.trycloudflare.com/auth/shopify/callback",
  "https://kiss-webshots-accurate-threats.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
