# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24bac162113225d71e4c458f5e51e049"
application_url = "https://digital-download-v2.fly.dev"
embedded = true
name = "Digital Downlaods"
handle = "digital_download_v2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products,read_customers"

[auth]
redirect_urls = [
  "https://digital-download-v2.fly.dev/auth/callback",
  "https://digital-download-v2.fly.dev/auth/shopify/callback",
  "https://digital-download-v2.fly.dev/api/auth/callback"
]

[pos]
embedded = false
